### ISSUE TITLE
Server crashes when used with new Cemu (v1.12)

### ISSUE THREAD

**Issue by Stephen-X** [denismr/iOSGyroForCemuhook#3]
I was trying to use the app with the new Cemu (I tested with v1.12, but this issue probably exists before this version), but the server crashed when I opened Cemu. Here's the error printout:
```
internal/buffer.js:35
    throw new ERR_OUT_OF_RANGE('value', `>= ${min} and <= ${max}`, value);
    ^

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received 3312645462408298
    at checkInt (internal/buffer.js:35:11)
    at writeU_Int32LE (internal/buffer.js:515:3)
    at Buffer.writeUInt32LE (internal/buffer.js:528:10)
    at BeginPacket (D:\Program Files\Games\Cemu\iOSGyroForCemuhook\app.js:51:8)
    at SendPacket (D:\Program Files\Games\Cemu\iOSGyroForCemuhook\app.js:63:15)
    at Socket.server.on (D:\Program Files\Games\Cemu\iOSGyroForCemuhook\app.js:132:7)
    at Socket.emit (events.js:182:13)
    at UDP.onMessage [as onmessage] (dgram.js:670:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ios-gyro-for-cemuhook@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ios-gyro-for-cemuhook@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Does anybody know what's going wrong? Thanks!

**Comment by johnnym90** [comment]
I've got the same problem, same thing happens when trying to use padtest. I've tried using another router, running as admin and changing port.

**Comment by johnnym90** [comment]
Oh, this worked for me https://github.com/hjmmc/WebGyroForCemuhook/releases

**Comment by Stephen-X** [comment]
@johnnym90 Thanks for the recommendation! Yes the new one works for me, although I have to use the packaged executable from release; if I run the source code directly with npm, I still face the same issue as shown above. I wonder what's the issue here?
